# Generated by Django 3.2.8 on 2021-10-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20211021_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
